GET http://localhost:3000/api/livros

###

GET http://localhost:3000/api/livros/1

###

POST http://localhost:3000/api/livros
Content-Type: application/json

{
  "titulo": "Título 50",
  "autor": "Autor 2",
  "anoPublicacao": 2023,
  "genero": "Ação",
  "estoqueQuantidade": 5
}

###

PATCH http://localhost:3000/api/livros/1
Content-Type: application/json

{
  "titulo": "Título 1"
}

###

DELETE http://localhost:3000/api/livros/2

###

POST http://localhost:3000/api/register
Content-Type: application/json

{
  "email": "gusalbukrk@outlook.com",
  "senha": "123456"
}