"use client";

import { FaPlus } from "react-icons/fa";
import { useState } from "react";

import { Livro } from "../generated/prisma";
import LivroForm from "./LivroForm";
import { getModalElement } from "../utils";

function CreateButton({
  onSuccess,
}: {
  onSuccess: (livroEdited: Livro) => void;
}) {
  const [livro, setLivro] = useState<Livro>({
    titulo: "",
    autor: "",
    anoPublicacao: new Date().getFullYear(),
    genero: "",
    estoqueQuantidade: 0,
  } as Livro); // excluding id, createdAt, updatedAt because they're generated by database

  return (
    <>
      <button
        className="btn flex gap-2 mb-5"
        onClick={() => getModalElement(`create_modal`).showModal()}
      >
        <FaPlus className="text-base" /> Criar livro
      </button>
      <dialog id={`create_modal`} className="modal">
        <div className="modal-box">
          <LivroForm method="POST" livro={livro} onSuccess={onSuccess} />
          {/* <h1>my modal</h1> */}
        </div>
      </dialog>
    </>
  );
}

export default CreateButton;
